[build-system]
requires = [
    "setuptools >= 35.0.2",
    "setuptools_scm >= 2.0.0, <3"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 80
skip-string-normalization = 'True'
skip-magic-trailing-comma = 'True'

[tool.isort]
profile = "black"
skip = [".tox", ".venv"]